#ifndef _CONF_
#define _CONF_


#if ROTATION == 0
#  define GLOBAL_ROTATION	0
#  define LVGL_ROTATION		LV_DISPLAY_ROTATION_0
#elif ROTATION == 90
#  define GLOBAL_ROTATION	1
#  define LVGL_ROTATION		LV_DISPLAY_ROTATION_90
#elif ROTATION == 180
#  define GLOBAL_ROTATION	2
#  define LVGL_ROTATION		LV_DISPLAY_ROTATION_180
#elif ROTATION == 270
#  define GLOBAL_ROTATION	3
#  define LVGL_ROTATION		LV_DISPLAY_ROTATION_270
#endif


#define JOYSTICK_TRIGGER_THRESAHOLD	0.3

#endif /* _CONF_ */