#!/usr/bin/env python3
"""Generate the firmware Unicode width tables from Python wcwidth data."""

from __future__ import annotations

from pathlib import Path

from wcwidth.table_wide import WIDE_EASTASIAN
from wcwidth.table_zero import ZERO_WIDTH


UNICODE_VERSION = "15.0.0"


def format_intervals(name: str, intervals: tuple[tuple[int, int], ...]) -> str:
    rows = [
        f"    {{0x{start:06X}u, 0x{end:06X}u}},"
        for start, end in intervals
    ]
    return (
        f"constexpr Interval {name}[] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    output = root / "src" / "unicode_width.cpp"
    zero = ZERO_WIDTH[UNICODE_VERSION]
    wide = WIDE_EASTASIAN[UNICODE_VERSION]
    source = f"""// Generated by tools/generate_unicode_width.py.
// Source: Python wcwidth Unicode {UNICODE_VERSION} interval tables.

#include "unicode_width.h"

#include <stddef.h>

namespace terminal {{
namespace unicode {{
namespace {{

struct Interval {{
    uint32_t first;
    uint32_t last;
}};

{format_intervals("kZeroWidth", zero)}
{format_intervals("kWide", wide)}
template <size_t Count>
bool contains(const Interval (&intervals)[Count], uint32_t codepoint)
{{
    size_t low = 0;
    size_t high = Count;
    while (low < high) {{
        const size_t middle = low + (high - low) / 2;
        const Interval& interval = intervals[middle];
        if (codepoint < interval.first) {{
            high = middle;
        }} else if (codepoint > interval.last) {{
            low = middle + 1;
        }} else {{
            return true;
        }}
    }}
    return false;
}}

}} // namespace

bool isValidScalar(uint32_t codepoint)
{{
    return codepoint <= 0x10FFFFu
        && !(codepoint >= 0xD800u && codepoint <= 0xDFFFu);
}}

ColumnWidth columnWidth(uint32_t codepoint)
{{
    if (!isValidScalar(codepoint)) {{
        return ColumnWidth::Control;
    }}
    if (codepoint == 0) {{
        return ColumnWidth::Zero;
    }}
    if (codepoint < 0x20u || (codepoint >= 0x7Fu && codepoint < 0xA0u)) {{
        return ColumnWidth::Control;
    }}
    if (contains(kZeroWidth, codepoint)) {{
        return ColumnWidth::Zero;
    }}
    if (contains(kWide, codepoint)) {{
        return ColumnWidth::Wide;
    }}
    return ColumnWidth::Narrow;
}}

}} // namespace unicode
}} // namespace terminal
"""
    output.write_text(source, encoding="ascii", newline="\n")
    print(
        f"generated {output} with {len(zero)} zero-width and "
        f"{len(wide)} wide intervals"
    )


if __name__ == "__main__":
    main()
