[env:tab5_min_uart_terminal]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
framework = arduino
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio

upload_speed = 1500000
monitor_speed = 115200
monitor_filters =
    time
    esp32_exception_decoder

build_type = debug

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    https://github.com/M5Stack/M5Unified.git
    https://github.com/M5Stack/M5GFX.git
    https://github.com/m5stack/M5Unit-KEYBOARD.git#0.1.0

[env:tab5_min_uart_terminal_fixed_debug]
extends = env:tab5_min_uart_terminal
build_flags =
    ${env:tab5_min_uart_terminal.build_flags}
    -DTERMINAL_FORCE_FIXED_CELL_RENDERING=1

[env:tab5_usb_keyboard_probe]
extends = env:tab5_min_uart_terminal
build_flags =
    ${env:tab5_min_uart_terminal.build_flags}
    -DENABLE_USB_KEYBOARD_PROBE=1
    -DENABLE_TAB5_KEYBOARD=0
    -DTERMINAL_FORCE_FIXED_CELL_RENDERING=1

[env:tab5_power_status_probe]
extends = env:tab5_min_uart_terminal
build_flags =
    ${env:tab5_min_uart_terminal.build_flags}
    -DENABLE_POWER_STATUS_DIAGNOSTICS=1
    -DTERMINAL_FORCE_FIXED_CELL_RENDERING=1

[env:tab5_terminal_cdc_inject]
extends = env:tab5_min_uart_terminal
build_flags =
    ${env:tab5_min_uart_terminal.build_flags}
    -DENABLE_TERMINAL_CDC_INJECTION=1
    -DENABLE_TAB5_KEYBOARD=0
    -DTERMINAL_FORCE_FIXED_CELL_RENDERING=1

[env:tab5_terminal_font_prop_preview]
extends = env:tab5_min_uart_terminal
build_flags =
    ${env:tab5_min_uart_terminal.build_flags}
    -DENABLE_TERMINAL_CDC_INJECTION=1
    -DENABLE_TAB5_KEYBOARD=0
    -DTERMINAL_FORCE_FIXED_CELL_RENDERING=0

[env:tab5_terminal_font_prop_fixed_debug]
extends = env:tab5_terminal_cdc_inject
