#pragma once

#define USB_DEBUG_BAUD 115200

#define LOGIN_UART_DEFAULT_BAUD 115200
#define LOGIN_UART_RX_PIN 7
#define LOGIN_UART_TX_PIN 6
#define LOGIN_UART_RX_BUFFER_SIZE 8192
#define LOGIN_UART_NVS_NAMESPACE "tab5term"
#define LOGIN_UART_NVS_BAUD_KEY "login_baud"

#ifndef ENABLE_USB_LOGIN_UART_BRIDGE
#define ENABLE_USB_LOGIN_UART_BRIDGE 1
#endif

#ifndef ENABLE_USB_BRIDGE_DEBUG_LOG
#define ENABLE_USB_BRIDGE_DEBUG_LOG 0
#endif

#ifndef ENABLE_POWER_DETECT_PROBE
#define ENABLE_POWER_DETECT_PROBE 0
#endif

#ifndef ENABLE_USB_KEYBOARD_PROBE
#define ENABLE_USB_KEYBOARD_PROBE 0
#endif

#ifndef ENABLE_TAB5_KEYBOARD
#define ENABLE_TAB5_KEYBOARD 1
#endif

#ifndef ENABLE_POWER_STATUS_DIAGNOSTICS
#define ENABLE_POWER_STATUS_DIAGNOSTICS 0
#endif

#ifndef ENABLE_TERMINAL_CDC_INJECTION
#define ENABLE_TERMINAL_CDC_INJECTION 0
#endif

#ifndef ENABLE_TERMINAL_STATE_DIAGNOSTICS
#define ENABLE_TERMINAL_STATE_DIAGNOSTICS 0
#endif

#ifndef ENABLE_SCREEN_CAPTURE_DIAGNOSTICS
#define ENABLE_SCREEN_CAPTURE_DIAGNOSTICS 0
#endif

#define TERMINAL_CDC_INJECTION_BYTES_PER_LOOP 128

#define INPUT_EVENT_QUEUE_LENGTH 256
#define USB_KEYBOARD_INPUT_QUEUE_LENGTH 256
#define TAB5_KEYBOARD_SDA_PIN 0
#define TAB5_KEYBOARD_SCL_PIN 1
#define TAB5_KEYBOARD_INT_PIN 50
#define USB_KEYBOARD_HOST_TASK_STACK_SIZE 4096
#define USB_KEYBOARD_CLIENT_TASK_STACK_SIZE 6144
#define USB_KEYBOARD_HOST_TASK_PRIORITY 2
#define USB_KEYBOARD_CLIENT_TASK_PRIORITY 4

#define SCREEN_ORIENTATION_STANDARD 0
#define SCREEN_ORIENTATION_KEYBOARD_MOUNTED 1

#ifndef SCREEN_ORIENTATION
#define SCREEN_ORIENTATION SCREEN_ORIENTATION_KEYBOARD_MOUNTED
#endif

#define TERMINAL_FONT_FACE_ASCII8X16 0
#define TERMINAL_FONT_FACE_DEJAVU18 1

#define TERMINAL_RENDER_MODE_FIXED_CELL 0
#define TERMINAL_RENDER_MODE_PROPORTIONAL 1

#ifndef TERMINAL_FONT_FACE
#define TERMINAL_FONT_FACE TERMINAL_FONT_FACE_DEJAVU18
#endif

#ifndef TERMINAL_RENDER_MODE
#define TERMINAL_RENDER_MODE TERMINAL_RENDER_MODE_PROPORTIONAL
#endif

#ifndef TERMINAL_FORCE_FIXED_CELL_RENDERING
#define TERMINAL_FORCE_FIXED_CELL_RENDERING 1
#endif

#ifndef TERMINAL_PROPORTIONAL_GLYPH_GAP
#define TERMINAL_PROPORTIONAL_GLYPH_GAP 1
#endif

#ifndef TERMINAL_PROPORTIONAL_MIN_ADVANCE
#define TERMINAL_PROPORTIONAL_MIN_ADVANCE 2
#endif

#ifndef TERMINAL_TEXT_SIZE
#define TERMINAL_TEXT_SIZE 1
#endif

#ifndef TERMINAL_CELL_WIDTH
#define TERMINAL_CELL_WIDTH 18
#endif

#ifndef TERMINAL_CELL_HEIGHT
#define TERMINAL_CELL_HEIGHT 20
#endif

#define TERMINAL_COLUMNS 64
#define TERMINAL_ROWS 32
#define TERMINAL_VERTICAL_MARGIN_ROWS 1

#define STATUS_BAR_HEIGHT 32
