#pragma once

#define USB_DEBUG_BAUD 115200

#define LOGIN_UART_BAUD 115200
#define LOGIN_UART_RX_PIN 7
#define LOGIN_UART_TX_PIN 6
#define ENABLE_USB_LOGIN_UART_BRIDGE 1
#define ENABLE_USB_BRIDGE_DEBUG_LOG 0

#define SCREEN_ROTATION 1
#define TERMINAL_TEXT_SIZE 2
#define STATUS_BAR_HEIGHT 32
