#define Enable_longPress_Continuous
#define SIGNAL_INPUT_PIN		1
#define SCREEN_ROTAION			3
#define ADC_SAMPLE_RATE			80000
// #define ADC_SAMPLE_RATE			SOC_ADC_SAMPLE_FREQ_THRES_HIGH
#define SAMPLE_BUFFLEN_BASE		1024U
#define SAMPLE_BUFFLEN			((2 * SAMPLE_BUFFLEN_BASE))

#define ADC_READ_MAX_VAL		4095
#define ADC_VOLTREAD_CAP		3100